# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: GPL-3.0-or-later

services:

  wanda:
    image: ghcr.io/trento-project/trento-wanda:rolling
    environment:
      DATABASE_URL: ecto://postgres:postgres@postgres/postgres
      SECRET_KEY_BASE: dummyS3cr3t
      AMQP_URL: amqp://wanda:wanda@rabbitmq
      CORS_ENABLED: "false"
      CATALOG_PATH: /app/catalog
      TOKEN_AUTHENTICATION_ENABLED: "false"
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 4000:4000
    entrypoint: /bin/sh -c "/app/bin/wanda eval \"Wanda.Release.init()\" && /app/bin/wanda start"
    volumes:
      - ./checks:/usr/share/trento/checks:ro

  rabbitmq:
    # Keep versions in sync with
      # .github/workflows/ci.yaml
      # https://github.com/trento-project/helm-charts/blob/main/charts/trento-server/charts/rabbitmq/values.yaml
    image: rabbitmq:3.12.6-management-alpine # https://hub.docker.com/_/rabbitmq/tags
    ports:
      - 5676:5671
      - 5674:5672
      - 15674:15672
    environment:
      RABBITMQ_DEFAULT_USER: wanda
      RABBITMQ_DEFAULT_PASS: wanda

  postgres:
    # Keep versions in sync with
      # .github/workflows/ci.yaml
      # https://github.com/trento-project/helm-charts/blob/main/charts/trento-server/values.yaml
      # https://documentation.suse.com/sles-sap/trento/single-html/SLES-SAP-trento/SLES-SAP-trento.html#id-install-postgresql
    image: registry.suse.com/suse/postgres:17.5 # https://registry.suse.com/repositories/suse-postgres17?tag=17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5434:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
