# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: GPL-3.0-or-later

name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - "VERSION"
      - "CHANGELOG.md"
  pull_request:
    types: [opened, synchronize, labeled]
    paths-ignore:
      - "VERSION"
  workflow_dispatch:

jobs:
  tlint:
    name: Lint checks
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/trento-project/tlint:latest
      volumes:
        - ${{ github.workspace }}:/data
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: apache/skywalking-eyes/header@61275cc80d0798a405cb070f7d3a8aaf7cf2c2c1 # v0.8.0
        name: Check license headers

      - name: Run TLint
        run: "/home/tlint/tlint lint /data/checks"

  publish-containers:
    name: Publish GHCR Containers
    needs:
      - tlint
    if: >-
      github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: trento-project/.github/.github/workflows/publish-containers.yaml@406be0972195864a87ed454458eaa0856d0c5457 # v1.6.0
    with:
      image_name: checks
      tag: rolling
    secrets:
      gh_token: ${{ secrets.TRENTOBOT_GH_PAT }}
      ssh_key: ${{ secrets.TRENTOBOT_SSH_KEY }}

  obs-sync:
    name: OBS sync
    if: >-
      fromJSON(vars.OBS_ENABLED)
      && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    uses: trento-project/.github/.github/workflows/obs-sync.yaml@406be0972195864a87ed454458eaa0856d0c5457 # v1.6.0
    needs:
      - tlint
    with:
      obs_project: ${{ vars.OBS_PROJECT_ROLLING }}
      obs_package: ${{ vars.OBS_PACKAGE }}
    secrets:
      gh_token: ${{ secrets.TRENTOBOT_GH_PAT }}
      obs_user: ${{ secrets.OBS_USER }}
      obs_pass: ${{ secrets.OBS_PASS }}
      obs_ssh_key: ${{ secrets.OBS_SSH_KEY }}
